### ISSUE TITLE
Gh-Pages

### ISSUE THREAD

**Issue by 0xMRTT** [topgrade-rs/topgrade-rs.github.io#1]
Hey, 

Since i don't have another way for contacting you, i'm using gh-issues.

I wanted to ask you if you are getting a 404 error while trying to access to https://topgrade-rs.github.io/. Sometimes it's a bit slow for me.

Otherwise, that's mean that there's a mess in the config

Thanks in advance

**Comment by s34m** [comment]
Works now, the wrong branch was selected as a source in the settings.

**Comment by 0xMRTT** [comment]
Lol, i forgot that because i thought that github will automaticly choose this branch. Thanks :+1:
